export type AppEventType =
  | ""
  | "didDrawCanvas"
  | "selectAll"
  | "delete"
  | "undo"
  | "redo"
  | "zoomIn"
  | "zoomOut"
  | "mouseMove"
  | "mouseDrag"
  | "mouseDown"
  | "mouseUp"
  | "keyDown"
  | "stopInteraction"
  | "startInteraction";
