language: node_js
node_js: stable
dist: trusty
sudo: required

install:
  - yarn install

script:
  - scripts/prebuild.sh
  - yarn test
  - yarn build

before_deploy:
  - cd build

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true

git:
  depth: 9999
