language: node_js
node_js: 11.10.0
dist: trusty
sudo: required

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - yarn install

script:
  - scripts/prebuild.sh
  # - yarn test
  - yarn build

before_deploy:
  - cp web.config build/
  - cd build

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on:
    all_branches: true

git:
  depth: 9999
