export const SET_WORKSPACE_ID = "SET_WORKSPACE_ID";
export const SET_SELECTED_DEVICE = "SET_SELECTED_DEVICE";

export const SET_DEVICES = "SET_DEVICES";
export const LOAD_DEVICES = "LOAD_DEVICES";
export const ADD_DEVICE = "ADD_DEVICE";

export const MOUSE_DOWN = "MOUSE_DOWN";
export const MOUSE_UP = "MOUSE_UP";
export const MOUSE_MOVE = "MOUSE_MOVE";

export const SET_CANVAS_SIZE = "SET_CANVAS_SIZE";
export const SET_CURSOR_POSITION = "SET_CURSOR_POSITION";

export const ADD_DYNAMIC_ITEM = "ADD_DYNAMIC_ITEM";
export const REMOVE_DYNAMIC_ITEM = "REMOVE_DYNAMIC_ITEM";
export const ADD_GRAPHIC_ITEM = "ADD_GRAPHIC_ITEM";
export const SET_GRAPHIC_ITEMS = "SET_GRAPHIC_ITEMS";

export const START_INTERACTION = "START_INTERACTION";

export const SET_PROJECT_ID = "SET_PROJECT_ID";
export const SET_PAGE = "SET_PAGE";

export const LOAD_GRAPHIC = "LOAD_GRAPHIC";
export const SAVE_GRAPHIC_ITEM = "SAVE_GRAPHIC_ITEM";
