export const CHANGE_VIEW = "CHANGE_VIEW";

export const ENABLE_SHORTCUT_HANDLER = "ENABLE_SHORTCUT_HANDLER";
export const ENABLE_PLACEMENT_TOOLBAR = "ENABLE_PLACEMENT_TOOLBAR";

export const SET_COPY_DATA = "SET_COPY_DATA";
export const VIEW_CHANGED = "VIEW_CHANGED";
export const REDRAWN = "REDRAWN";
export const SET_SELECTED_PLACEMENT_IDS =
  "SET_SELECTED_PLACEMENT_IDS";

export const UNDO_REDO_ADD_START_MARKER =
  "UNDO_REDO_ADD_START_MARKER";
export const UNDO_REDO_ADD = "UNDO_REDO_ADD";
export const UNDO_REDO_SET_INDEX = "UNDO_REDO_SET_INDEX";

export const SET_CANVAS_SIZE = "SET_CANVAS_SIZE";
export const SET_VIEWPORT = "SET_VIEWPORT";

export const SET_PLACEMENT = "SET_PLACEMENT";
export const ADD_PLACEMENT = "ADD_PLACEMENT";
export const DELETE_PLACEMENT = "DELETE_PLACEMENT";

export const DELETE_LAYER = "DELETE_LAYER";

export const UPDATE_PLACEMENT = "UPDATE_PLACEMENT";

// Symbols
export const SET_SYMBOLS = "SET_SYMBOLS";
export const ADD_SYMBOL = "ADD_SYMBOL";

export const SET_PROJECT_ID = "SET_PROJECT_ID";
export const SET_PAGE_ID = "SET_PAGE_ID";

export const SET_PAGES = "SET_PAGES";
// export const LOAD_PAGES = "LOAD_PAGES";
export const ADD_PAGE = "ADD_PAGE";
export const UPDATE_PAGE = "UPDATE_PAGE";

export const USE_GRID = "USE_GRID";

export const SHOW_MODAL = "SHOW_MODAL";

export const SET_ERROR = "SET_ERROR";
