export const IA_SELECT = "IA_SELECT";
export const IA_MOVE = "IA_MOVE";
export const IA_CREATE_LINE = "IA_CREATE_LINE";
export const IA_CREATE_CIRCLE = "IA_CREATE_CIRCLE";
export const IA_CREATE_GROUP = "IA_CREATE_GROUP";
export const IA_CREATE_SYMBOL = "IA_CREATE_SYMBOL";
export const IA_ZOOM_WINDOW = "IA_ZOOM_WINDOW";
export const IA_DELETE_ITEM = "IA_DELETE_ITEM";
export const IA_CREATE_SYMBOLREF = "IA_CREATE_SYMBOLREF";
export const IA_CREATE_POLYGON = "IA_CREATE_POLYGON";
export const IA_CREATE_CONNECTION_POINT =
  "IA_CREATE_CONNECTION_POINT";
